

from main import main

try:
    main()

except Exception as e:
	print e